name: Setup Node
description: Sets up node and pnpm
inputs:
  version: # determines what node version to install
    required: false
    description: node js version
    default: 20
runs:
  using: composite
  steps:
    - uses: nrwl/nx-set-shas@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.version}}
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    


